"""changes in user and gym

Revision ID: 405e825775f2
Revises: 980972e4edaa
Create Date: 2025-11-26 01:35:10.461666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405e825775f2'
down_revision = '980972e4edaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
