"""changes in user and gym

Revision ID: 980972e4edaa
Revises: 9e5dfe086368
Create Date: 2025-11-26 01:06:15.114387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '980972e4edaa'
down_revision = '9e5dfe086368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('valid_till', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gym_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_members',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gym_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('gym_members_gym_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('gym_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'gym_id', name=op.f('gym_members_pkey'))
    )
    op.drop_table('gym_enrollments')
    # ### end Alembic commands ###
